<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Utilities\IMenuTabRepository.cs" />
    <Compile Remove="Services\Utilities\IUserService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Delta.Core\Delta.Core.csproj" />
    <ProjectReference Include="..\Delta.Domain\Delta.Domain.csproj" />
    <ProjectReference Include="..\Delta.Shared\Delta.Shared.csproj" />
  </ItemGroup>

</Project>
